services:
  - type: web
    name: lifskill-backend
    env: go
    buildCommand: cd backend && go build -o main
    startCommand: cd backend && ./main
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: lifskill-db
          property: connectionString
      - key: RENDER
        value: true
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://lifeskill-web-frontend.onrender.com
      - key: UPLOAD_DIR
        value: ./uploads

  - type: static
    name: lifskill-frontend
    buildCommand: cd frontend/lifskill_frontend && npm install && npm run build
    staticPublishPath: frontend/lifskill_frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://lifskill-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: lifskill-db
    databaseName: lifeskill
    user: lifskill_user
    plan: free 